# Generated by Django 4.0 on 2022-01-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_alter_user_id_comment_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXaRKTiE4Cu5dK-7WDq03H_7BN25TAak8U2fOLKbctt4ySr9tkt1ByA2LO3Nz-bTZ6_eI&usqp=CAU'),
        ),
    ]
