# Generated by Django 4.0 on 2022-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='isclosed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
