# Generated by Django 4.0 on 2022-01-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_isclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='iswatch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
